/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MRouteRouteImport } from './routes/m/route'
import { Route as OwnerRouteRouteImport } from './routes/_owner/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as SetupTokenRouteImport } from './routes/setup.$token'
import { Route as MTasksRouteImport } from './routes/m/tasks'
import { Route as MReportIssueRouteImport } from './routes/m/report-issue'
import { Route as MProfileRouteImport } from './routes/m/profile'
import { Route as MHistoryRouteImport } from './routes/m/history'
import { Route as OwnerTodayRouteImport } from './routes/_owner/today'
import { Route as OwnerTasksRouteImport } from './routes/_owner/tasks'
import { Route as OwnerSettingsRouteImport } from './routes/_owner/settings'
import { Route as OwnerReportsRouteImport } from './routes/_owner/reports'
import { Route as OwnerPeopleRouteImport } from './routes/_owner/people'
import { Route as OwnerIssuesRouteImport } from './routes/_owner/issues'
import { Route as OwnerFieldsRouteImport } from './routes/_owner/fields'
import { Route as OwnerEquipmentRouteImport } from './routes/_owner/equipment'
import { Route as MTaskIdRouteImport } from './routes/m/task.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MRouteRoute = MRouteRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRouteRoute = OwnerRouteRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRouteRoute,
} as any)
const SetupTokenRoute = SetupTokenRouteImport.update({
  id: '/setup/$token',
  path: '/setup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MTasksRoute = MTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => MRouteRoute,
} as any)
const MReportIssueRoute = MReportIssueRouteImport.update({
  id: '/report-issue',
  path: '/report-issue',
  getParentRoute: () => MRouteRoute,
} as any)
const MProfileRoute = MProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MRouteRoute,
} as any)
const MHistoryRoute = MHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MRouteRoute,
} as any)
const OwnerTodayRoute = OwnerTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerTasksRoute = OwnerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerPeopleRoute = OwnerPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerIssuesRoute = OwnerIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerFieldsRoute = OwnerFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const OwnerEquipmentRoute = OwnerEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => OwnerRouteRoute,
} as any)
const MTaskIdRoute = MTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => MRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m': typeof MRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/equipment': typeof OwnerEquipmentRoute
  '/fields': typeof OwnerFieldsRoute
  '/issues': typeof OwnerIssuesRoute
  '/people': typeof OwnerPeopleRoute
  '/reports': typeof OwnerReportsRoute
  '/settings': typeof OwnerSettingsRoute
  '/tasks': typeof OwnerTasksRoute
  '/today': typeof OwnerTodayRoute
  '/m/history': typeof MHistoryRoute
  '/m/profile': typeof MProfileRoute
  '/m/report-issue': typeof MReportIssueRoute
  '/m/tasks': typeof MTasksRoute
  '/setup/$token': typeof SetupTokenRoute
  '/m/': typeof MIndexRoute
  '/m/task/$id': typeof MTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/equipment': typeof OwnerEquipmentRoute
  '/fields': typeof OwnerFieldsRoute
  '/issues': typeof OwnerIssuesRoute
  '/people': typeof OwnerPeopleRoute
  '/reports': typeof OwnerReportsRoute
  '/settings': typeof OwnerSettingsRoute
  '/tasks': typeof OwnerTasksRoute
  '/today': typeof OwnerTodayRoute
  '/m/history': typeof MHistoryRoute
  '/m/profile': typeof MProfileRoute
  '/m/report-issue': typeof MReportIssueRoute
  '/m/tasks': typeof MTasksRoute
  '/setup/$token': typeof SetupTokenRoute
  '/m': typeof MIndexRoute
  '/m/task/$id': typeof MTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_owner': typeof OwnerRouteRouteWithChildren
  '/m': typeof MRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_owner/equipment': typeof OwnerEquipmentRoute
  '/_owner/fields': typeof OwnerFieldsRoute
  '/_owner/issues': typeof OwnerIssuesRoute
  '/_owner/people': typeof OwnerPeopleRoute
  '/_owner/reports': typeof OwnerReportsRoute
  '/_owner/settings': typeof OwnerSettingsRoute
  '/_owner/tasks': typeof OwnerTasksRoute
  '/_owner/today': typeof OwnerTodayRoute
  '/m/history': typeof MHistoryRoute
  '/m/profile': typeof MProfileRoute
  '/m/report-issue': typeof MReportIssueRoute
  '/m/tasks': typeof MTasksRoute
  '/setup/$token': typeof SetupTokenRoute
  '/m/': typeof MIndexRoute
  '/m/task/$id': typeof MTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m'
    | '/login'
    | '/signup'
    | '/equipment'
    | '/fields'
    | '/issues'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/today'
    | '/m/history'
    | '/m/profile'
    | '/m/report-issue'
    | '/m/tasks'
    | '/setup/$token'
    | '/m/'
    | '/m/task/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/equipment'
    | '/fields'
    | '/issues'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/today'
    | '/m/history'
    | '/m/profile'
    | '/m/report-issue'
    | '/m/tasks'
    | '/setup/$token'
    | '/m'
    | '/m/task/$id'
  id:
    | '__root__'
    | '/'
    | '/_owner'
    | '/m'
    | '/login'
    | '/signup'
    | '/_owner/equipment'
    | '/_owner/fields'
    | '/_owner/issues'
    | '/_owner/people'
    | '/_owner/reports'
    | '/_owner/settings'
    | '/_owner/tasks'
    | '/_owner/today'
    | '/m/history'
    | '/m/profile'
    | '/m/report-issue'
    | '/m/tasks'
    | '/setup/$token'
    | '/m/'
    | '/m/task/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRouteRoute: typeof OwnerRouteRouteWithChildren
  MRouteRoute: typeof MRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SetupTokenRoute: typeof SetupTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/setup/$token': {
      id: '/setup/$token'
      path: '/setup/$token'
      fullPath: '/setup/$token'
      preLoaderRoute: typeof SetupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/tasks': {
      id: '/m/tasks'
      path: '/tasks'
      fullPath: '/m/tasks'
      preLoaderRoute: typeof MTasksRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/report-issue': {
      id: '/m/report-issue'
      path: '/report-issue'
      fullPath: '/m/report-issue'
      preLoaderRoute: typeof MReportIssueRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/profile': {
      id: '/m/profile'
      path: '/profile'
      fullPath: '/m/profile'
      preLoaderRoute: typeof MProfileRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/history': {
      id: '/m/history'
      path: '/history'
      fullPath: '/m/history'
      preLoaderRoute: typeof MHistoryRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/_owner/today': {
      id: '/_owner/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof OwnerTodayRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/tasks': {
      id: '/_owner/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof OwnerTasksRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/settings': {
      id: '/_owner/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/reports': {
      id: '/_owner/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/people': {
      id: '/_owner/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof OwnerPeopleRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/issues': {
      id: '/_owner/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof OwnerIssuesRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/fields': {
      id: '/_owner/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof OwnerFieldsRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/_owner/equipment': {
      id: '/_owner/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof OwnerEquipmentRouteImport
      parentRoute: typeof OwnerRouteRoute
    }
    '/m/task/$id': {
      id: '/m/task/$id'
      path: '/task/$id'
      fullPath: '/m/task/$id'
      preLoaderRoute: typeof MTaskIdRouteImport
      parentRoute: typeof MRouteRoute
    }
  }
}

interface OwnerRouteRouteChildren {
  OwnerEquipmentRoute: typeof OwnerEquipmentRoute
  OwnerFieldsRoute: typeof OwnerFieldsRoute
  OwnerIssuesRoute: typeof OwnerIssuesRoute
  OwnerPeopleRoute: typeof OwnerPeopleRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerTasksRoute: typeof OwnerTasksRoute
  OwnerTodayRoute: typeof OwnerTodayRoute
}

const OwnerRouteRouteChildren: OwnerRouteRouteChildren = {
  OwnerEquipmentRoute: OwnerEquipmentRoute,
  OwnerFieldsRoute: OwnerFieldsRoute,
  OwnerIssuesRoute: OwnerIssuesRoute,
  OwnerPeopleRoute: OwnerPeopleRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerTasksRoute: OwnerTasksRoute,
  OwnerTodayRoute: OwnerTodayRoute,
}

const OwnerRouteRouteWithChildren = OwnerRouteRoute._addFileChildren(
  OwnerRouteRouteChildren,
)

interface MRouteRouteChildren {
  MHistoryRoute: typeof MHistoryRoute
  MProfileRoute: typeof MProfileRoute
  MReportIssueRoute: typeof MReportIssueRoute
  MTasksRoute: typeof MTasksRoute
  MIndexRoute: typeof MIndexRoute
  MTaskIdRoute: typeof MTaskIdRoute
}

const MRouteRouteChildren: MRouteRouteChildren = {
  MHistoryRoute: MHistoryRoute,
  MProfileRoute: MProfileRoute,
  MReportIssueRoute: MReportIssueRoute,
  MTasksRoute: MTasksRoute,
  MIndexRoute: MIndexRoute,
  MTaskIdRoute: MTaskIdRoute,
}

const MRouteRouteWithChildren =
  MRouteRoute._addFileChildren(MRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRouteRoute: OwnerRouteRouteWithChildren,
  MRouteRoute: MRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SetupTokenRoute: SetupTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
